/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.view_login;
import view.view_produtos;


/**
 *
 * @author Adm
 */
public class view_principal extends javax.swing.JFrame {

    /**
     * Creates new form view_principal
     */
    public view_principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        dp = new javax.swing.JDesktopPane();
        painel_superior = new javax.swing.JPanel();
        user_icon = new javax.swing.JLabel();
        user_login = new javax.swing.JLabel();
        btn_menu_inicial = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        menus = new javax.swing.JMenuBar();
        menu_vendas = new javax.swing.JMenu();
        menu_vendas_vender = new javax.swing.JMenuItem();
        menu_vendas_historicoVendas = new javax.swing.JMenuItem();
        menu_compras = new javax.swing.JMenu();
        menu_compras_comprar = new javax.swing.JMenuItem();
        menu_compras_historicoCompras = new javax.swing.JMenuItem();
        menu_inventario = new javax.swing.JMenu();
        menu_inventario_produtos = new javax.swing.JMenuItem();
        menu_gestao = new javax.swing.JMenu();
        menu_gestao_clientes = new javax.swing.JMenuItem();
        menu_gestao_fornecedores = new javax.swing.JMenuItem();
        btnUsuarios = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(100, 200));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(786, 421));

        dp.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        dp.setLayout(new java.awt.GridLayout(1, 0));

        painel_superior.setBackground(new java.awt.Color(153, 0, 153));
        painel_superior.setForeground(new java.awt.Color(255, 255, 255));

        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatar_icon_small.png"))); // NOI18N

        user_login.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        user_login.setForeground(new java.awt.Color(255, 255, 255));
        user_login.setText("Usuário");

        btn_menu_inicial.setBackground(new java.awt.Color(153, 0, 153));
        btn_menu_inicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_menu_inicial.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu_inicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/color_swatch.png"))); // NOI18N
        btn_menu_inicial.setText("MENU INICIAL");
        btn_menu_inicial.setBorder(null);
        btn_menu_inicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_inicialActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_superiorLayout = new javax.swing.GroupLayout(painel_superior);
        painel_superior.setLayout(painel_superiorLayout);
        painel_superiorLayout.setHorizontalGroup(
            painel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_superiorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btn_menu_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(user_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        painel_superiorLayout.setVerticalGroup(
            painel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_superiorLayout.createSequentialGroup()
                .addComponent(user_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_superiorLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnSair))
                    .addGroup(painel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_menu_inicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user_login)))
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dp)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(painel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );

        dp.getAccessibleContext().setAccessibleName("");
        dp.getAccessibleContext().setAccessibleDescription("");

        menu_vendas.setText("Vendas");

        menu_vendas_vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/basket_add.png"))); // NOI18N
        menu_vendas_vender.setText("Efetuar Venda");
        menu_vendas.add(menu_vendas_vender);

        menu_vendas_historicoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder_page_white.png"))); // NOI18N
        menu_vendas_historicoVendas.setText("Histórico de Vendas");
        menu_vendas.add(menu_vendas_historicoVendas);

        menus.add(menu_vendas);

        menu_compras.setText("Compras");

        menu_compras_comprar.setText("Efetuar Compra");
        menu_compras.add(menu_compras_comprar);

        menu_compras_historicoCompras.setText("Histórico de Compras");
        menu_compras.add(menu_compras_historicoCompras);

        menus.add(menu_compras);

        menu_inventario.setText("Inventário");

        menu_inventario_produtos.setText("Produtos");
        menu_inventario_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_inventario_produtosActionPerformed(evt);
            }
        });
        menu_inventario.add(menu_inventario_produtos);

        menus.add(menu_inventario);

        menu_gestao.setText("Cadastro");

        menu_gestao_clientes.setText("Clientes");
        menu_gestao_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_gestao_clientesActionPerformed(evt);
            }
        });
        menu_gestao.add(menu_gestao_clientes);

        menu_gestao_fornecedores.setText("Fornecedores");
        menu_gestao_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_gestao_fornecedoresActionPerformed(evt);
            }
        });
        menu_gestao.add(menu_gestao_fornecedores);

        btnUsuarios.setText("Usuários");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        menu_gestao.add(btnUsuarios);

        jMenuItem2.setText("Produtos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_gestao.add(jMenuItem2);

        menus.add(menu_gestao);

        jMenu1.setText("Configurações");
        menus.add(jMenu1);

        setJMenuBar(menus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu_inicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_inicialActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_menu_inicialActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:      
        
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void menu_inventario_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inventario_produtosActionPerformed
        // TODO add your handling code here:
        
        
        view_produtos view_produtos = new view_produtos();
        dp.add(view_produtos);
        dp.moveToFront(view_produtos);
        view_produtos.setVisible(true);
        
        
    }//GEN-LAST:event_menu_inventario_produtosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        /*String x = view_produtos.x;
        if (x == null){
            view_produtos view_produtos = new view_produtos();
            dp.add(view_produtos);
            dp.moveToFront(view_produtos);
            view_produtos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, feche a janela existente!");
        }*/
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        view_login telaLogin = new view_login();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void menu_gestao_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_gestao_fornecedoresActionPerformed
        // TODO add your handling code here:
        
    }    
        
        
    }//GEN-LAST:event_menu_gestao_fornecedoresActionPerformed

    private void menu_gestao_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_gestao_clientesActionPerformed
        // TODO add your handling code here:
        
        
        
        //listar todos os clientes
        
        
    }//GEN-LAST:event_menu_gestao_clientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem btnUsuarios;
    private javax.swing.JButton btn_menu_inicial;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menu_compras;
    private javax.swing.JMenuItem menu_compras_comprar;
    private javax.swing.JMenuItem menu_compras_historicoCompras;
    private javax.swing.JMenu menu_gestao;
    private javax.swing.JMenuItem menu_gestao_clientes;
    private javax.swing.JMenuItem menu_gestao_fornecedores;
    private javax.swing.JMenu menu_inventario;
    private javax.swing.JMenuItem menu_inventario_produtos;
    private javax.swing.JMenu menu_vendas;
    private javax.swing.JMenuItem menu_vendas_historicoVendas;
    private javax.swing.JMenuItem menu_vendas_vender;
    private javax.swing.JMenuBar menus;
    private javax.swing.JPanel painel_superior;
    private javax.swing.JLabel user_icon;
    private javax.swing.JLabel user_login;
    // End of variables declaration//GEN-END:variables

